BIBSYSDEV/nva-nvi

index-handlers/src/main/java/no/sikt/nva/nvi/index/DeleteNviCandidateHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/OpenSearchClient.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/SearchClient.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/DeleteNviCandidateMessageBody.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/DeleteNviCandidateHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/FakeSearchClient.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java, template.yaml
Could be great to remove @JacocGenerated from OpenSearchClient, but for now it is not possible to test indexExists() method when throwing exception. 
I have also removed unused environment variables in template.
One more thing, it seems like OpenSearch is smart enough and does not create new document when document with matching id already exists. Which means we do not need to update(or delete and put new one) nvi candidate in index when update event from expansion comes.
=> Np 44995 remove candidate from index

event-handlers/build.gradle, event-handlers/src/main/java/handlers/UpsertNviCandidateHandler.java, event-handlers/src/main/java/handlers/UpsertRequest.java, event-handlers/src/test/java/handlers/UpsertNviCandidateHandlerTest.java, settings.gradle, template.yaml
Splitting Jira task (https://unit.atlassian.net/browse/NP-45083) into several PRs to keep them small. This is nr 1
- UpsertNviCandidateHandler consumes messages on sqs queue "NewCandidateQueue"
- Logs error if message body is invalid
- Logs error if publicationBucketUri is null
=> Np 45083 upsert nvi candidate handler validation

event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
Fix for bug: Should remove existing approvals when candidate exists and is no longer applicable
=> Np 45326 remove approval status if not applicable

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/NviCandidateRepository.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
Should update approval status when candidate has approval that has been reset
=> Fix: Update approval for candidate with reset approvals

event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/CandidateBO.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/exception/IllegalOperationException.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateBOApprovalStatusTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateBONotesTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateBOTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
UpsertNviCandidateHandler is logging lots of error for the following case: Evaluated candidate is not candidate and does not exist. This is wrong, UpsertNviCandidateHandler should do nothing in this case. Changes:
- CandidateBO.fromRequest(UpsertRequest ...) returns Optional.empty() in this case instead of throwing IllegalOperationException().
=> shouldDoNothingIfCreateRequestIsForNonCandidateThatDoesNotExist

nvi-evaluator/src/main/java/no/sikt/nva/nvi/evaluator/calculator/PointCalculator.java, nvi-evaluator/src/test/java/no/sikt/nva/nvi/evaluator/calculator/PointCalculatorTest.java
[Jira task](https://unit.atlassian.net/browse/NP-45420): Bug: Take into account contributors without affiliations in point calculation
Added counting creator shares for contributors without affiliations in point calculations
=> Np 45420 point calculation: count creator shares for contributors without affiliations

nvi-commons/src/main/resources/sparql/nvi.sparql, nvi-evaluator/src/test/java/no/sikt/nva/nvi/evaluator/EvaluateNviCandidateHandlerTest.java, nvi-evaluator/src/test/resources/candidate_publicationDate_before_2022.json
To prevent too many candidates when starting cristin-import in TEST in the following days, filtering away candidates with publication year before 2022.
=> shouldCreateNonCandidateWhenPublicationYearBefore2022

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/CandidateBO.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateBOTest.java
Jira issue: [Bug: Candidate not showing after being nonCandidate when no relevant fields are updated](https://unit.atlassian.net/browse/NP-45443)
If a candidate goes from candidate -> non candidate -> candidate, we need to generate new approvals, even if candidate data hasen't changed.
=> Np 45443 fix reset for non candidates

event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/CandidateBO.java, nvi-commons/src/main/resources/sparql/nvi.sparql, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateBOApprovalStatusTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateBOTest.java, nvi-evaluator/src/main/java/no/sikt/nva/nvi/evaluator/calculator/PointCalculator.java, nvi-evaluator/src/main/java/no/sikt/nva/nvi/evaluator/model/Level.java, nvi-evaluator/src/test/java/no/sikt/nva/nvi/evaluator/EvaluateNviCandidateHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
Changes in evaluater (EvaluateNviCandidateHandler):
- Should create candidate when level value in expanded resource has "version two" values (“Unassigned”, “LevelZero”, “LevelOne", “LevelTwo")
Changes during persistence of candidate:
- Enum DbLevel handles both version 1 and version 2 values when parsing a string to a DbLevel object.
=> Np 45529 Handle publication channel v2 level values 

buildSrc/src/main/groovy/nva.nvi.java-conventions.gradle, nvi-evaluator/src/main/java/no/sikt/nva/nvi/evaluator/calculator/PointCalculator.java, nvi-evaluator/src/test/java/no/sikt/nva/nvi/evaluator/calculator/PointCalculatorTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
Jira task: [Creator shares (forfatterandeler) should not be counted for unverified affiliations](https://unit.atlassian.net/browse/NP-45535)
Creator share count changed from:
`(Number of combinations of author and affiliations) + (number of authors with without affiliations)`
to:
`(Number of combinations of author and verified affiliations) + (number of authors (with only unverified affiliations OR without affiliations))`
(Also changed failFast = false in java conventions)
=> Np 45535 point calculation unverified affiliations

docs/openapi.yaml, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchReportHandler.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/model/Excel.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchReportHandlerTest.java, template.yaml
Rename path parameter institutionIdentifier to institutionId in FetchReportHandler. Remove plus sign from open api spec and handler, not necessary
=> Fix FetchReportHandler path parameter

nvi-commons/src/main/java/no/sikt/nva/nvi/common/DatabaseConstants.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateRepositoryTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/LocalDynamoTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java, template.yaml
Jira task: [Tool for re-evaluating nvi candidates](https://unit.atlassian.net/browse/NP-45666)
New access pattern needed in DB: _Get all candidates published in given year_
- Added a new secondary index: SearchByYear
- Added method in CandidateRepository to fetch candidates for a given year with `startMarker` and `pageSize` (for pagination)
=> Np 45666 Secondary index: SearchByYear

event-handlers/build.gradle, event-handlers/src/main/java/no/sikt/nva/nvi/events/QueuePersistedResourceHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandler.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/QueuePersistedResourceHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateWithCristinDataTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/FakeSqsClient.java, template.yaml
Removing onSuccess destinations for EvaluateNVICandidateHandler and QueuePersistedResourceHandler, and replacing with queue client initiated in handler.
Also added redrive policies (DLQ-config) to NewCandidateQueue and PersistedResourceQueue
=> Remove lambda onSuccess destinations

event-handlers/build.gradle, event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/PersistedResourceMessage.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/ReEvaluateRequest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/FakeSqsClient.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/ListingResult.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/ListingResultWithCandidates.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/NviQueueClient.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/NviSendMessageResponse.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/QueueClient.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateRepositoryTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/queue/NviQueueClientTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java, template.yaml
Last part of jira task: [Tool for re-evaluating nvi candidates](https://unit.atlassian.net/browse/NP-45666)
Implemented new handler: `ReEvaluateCandidatesHandler`, this handler:
- Takes input `ReEvaluateRequest` with required field `year`
- Scans through the `SearchByYear` index (with pagination)
- Puts a `SQSEevent` (batches of 10) on the `PersistedResourceQueue` (consumed by `EvaluateNviCandidateHandler`)
- If there are more candidates to scan, the handler emits a new event to be consumed by itself on the EventBrigde topic `NviService.ReEvaluate`
Also added a DLQ for this handler: `ReEvaluateDLQ`
=> Np 45666- ReEvaluateNviCandidatesHandler

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/calculator/PointCalculator.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/resources/evaluator/candidate_academicArticle.json, event-handlers/src/test/resources/evaluator/candidate_academicArticle_deprecated.json, event-handlers/src/test/resources/evaluator/candidate_academicChapter.json, event-handlers/src/test/resources/evaluator/candidate_academicChapter_deprecated.json, event-handlers/src/test/resources/evaluator/candidate_academicChapter_seriesLevelEmptyPublisherLevelOne.json, event-handlers/src/test/resources/evaluator/candidate_academicLiteratureReview.json, event-handlers/src/test/resources/evaluator/candidate_academicLiteratureReview_deprecated.json, event-handlers/src/test/resources/evaluator/candidate_academicMonograph.json, event-handlers/src/test/resources/evaluator/candidate_academicMonograph_deprecated.json, event-handlers/src/test/resources/evaluator/candidate_academicMonograph_series_multiple_types.json, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java
Noticed jackson error logged by `EvaluateNviCandidateHandler` for academic chapters and monographs because json pointer for series `level` did not support the new field name `scientificValue`.
Impemented support for both field names `level` an `scientificValue`, and marked old json pointers with Deprecated annotation
=> Fix: Pointcalculator extractChannelLevel

index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexDocumentHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/UpdateIndexHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/S3StorageWriter.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Affiliation.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Approval.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Contributor.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/StorageWriter.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java
First version of `IndexDocumentHandler`, there is more to come covering rest of tests for todays `UpdateIndexHandler`.
Implemented "happy case" and error handling (except for sending message to common DLQ, see todo)).
Worried the error handling implementation is a bit of an overkill? Should I extract most of the implementation to a `IndexDocumentService` and have more of a catch-all error handling? Let med know your thoughts :)
=> Np 45509 index document handler

event-handlers/build.gradle, event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DynamoDbEventToQueueHandler.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DynamoDbEventToQueueHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/FakeSqsClient.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/NviQueueClient.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/QueueClient.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/queue/NviQueueClientTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/DynamoDbTestUtils.java
`DynamoDbEventToQueueHandler`: Should send message to DLQ with `messageAttribute` `candidateIdentifier` when handling error.
See DLQ in diagram in [Jira task](https://unit.atlassian.net/browse/NP-45509)
(Cfn for DLQ coming later)
=> DynamoDbEventToQueueHandler DLQ

event-handlers/build.gradle, event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandler.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/FakeNotificationClient.java, gradle/libs.versions.toml, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, nvi-commons/build.gradle, nvi-commons/src/main/java/no/sikt/nva/nvi/common/notification/NotificationClient.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/notification/NviNotificationClient.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/notification/NviPublishMessageResponse.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/NviQueueClient.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/notification/NviNotificationClientTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/DynamoDbTestUtils.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/QueueServiceTestUtils.java
First, simple version of `DataEntryUpdateHandler`. Only implemented handling of dynamoDb events for `CandidateDao`. See todos, handling of rest of the dao types coming in next PR.
=> Np 45509 DataEntryUpdateHandler

index-handlers/src/main/java/no/sikt/nva/nvi/index/RemoveIndexDocumentHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/UpdateIndexHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/OpenSearchClient.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/SearchClient.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/RemoveIndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/DynamoDbTestUtils.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/QueueServiceTestUtils.java
`RemoveIndexDocumentHandler` is triggered by a new queue `RemoveDocumentFromIndexQueue` which subscribes to topics `nvi-data-entry-update-candidate-not-applicable-update` and `nvi-data-entry-update-candidate-remove` (not in template yet) and removes the document from `OpenSearch`.
=> Np 45509 RemoveIndexDocumentHandler

event-handlers/src/test/java/no/sikt/nva/nvi/events/QueuePersistedResourceHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DynamoDbEventToQueueHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateWithCristinDataTest.java, index-handlers/build.gradle, index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexDocumentHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/PersistedIndexDocumentMessage.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java, nvi-test/build.gradle, nvi-test/src/main/java/no/sikt/nva/nvi/test/FakeSqsClient.java
The plan was to listen to S3 events, but this is not possible when the bucket is in another stack. Therefore, added new functionality in IndexDocumentHandler:
- send event with s3 uri when document is persisted
=> Np 45509 IndexDocumentHandler: Send event after persisting index document

event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateUniquenessEntryDao.java
Fix: DataEntryUpdateHandler handle CandidateUniquenessEntryDao
Did not fix the three codacy issues because the fields are DynamoDbAttributes
=> Fix: DataEntryUpdateHandler handle candidateUniquenessEntryDao

template.yaml
Having issues with messages not being sent to DLQs when unexpected errors occur for lamda functions
- Added redrive policies for queues with max retries and DLQs
- Also tried to organise the SQS config in the template
=> Dlq settings: Redrive policies

event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/queue/NviQueueClient.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/queue/NviQueueClientTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/FakeSqsClient.java
Fix `SqsException` that occurred when sending message to DLQ with `messageAttribute` `candidateIdentifier`. `messageAttribute` must contain `dataType`:
```
Message (user) attribute 'candidateIdentifier' must contain a non-empty attribute type. 
(Service: Sqs, Status Code: 400, Request ID: a7807667-a3f1-583f-a487-287657b4c0c2):software.amazon.awssdk.services.sqs.model.SqsException
software.amazon.awssdk.services.sqs.model.SqsException: Message (user) attribute 'candidateIdentifier' must contain a non-empty attribute type.
```
=> Add dataType to messageAttribute

event-handlers/build.gradle, event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DynamoDbUtils.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DynamoDbUtilsTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/DynamoDbTestUtils.java
Jira bug: [Candidate modifications/approvals are not getting indexed](https://unit.atlassian.net/browse/NP-45929)
Reason: `AttributeValue`s with null-values where not parsed correctly with `dynamoDbMapper` (ObjectMapper) in `DynamoDbUtils`, causing failures in `DynamoEntryWithRangeKey.parseAttributeValuesMap()`.
Not a fan of this solution, its very aws dynamoDb model-specific. Feel free to suggest better ways to handle this issue.
=> Fix attribute value bug

template.yaml
- Timeout for NviRequeueDlqHandler adjusted to 5 minutes
- Reserved concurrency for `IndexDocumentHandler` set to 25 (due to cristin-proxy requests)
- Reserved concurrency for `UpdateIndexHandler` set to 50 (due to OpenSearch requests)
The reserved concurrencies are probable on the safer side, but can work as a default and be changed in aws if needed
=> Template config - timeout and reserved concurrency

index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexDocumentHandler.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
To avoid race condition between `IndexDocumentHandler` and `RemoveIndexDocumentHandler` in the case candidate -> non candidate (see diagram), added a check in `IndexDocumentHandler` if the candidate is applicable before producing index document.
=> shouldNotBuildIndexDocumentIfCandidateIsNotApplicable

template.yaml
Noticed that nvi queues where missing prefixes with stack names in aws console compared to the other queues. These are provided as defaults if name is not specified.
Therefore: removing queue names from template
=> Remove SQS queue names, use aws default names

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
In order to not get a blank node in a graph database, add `id` to `NviCandidateIndexDocument`
=> Add id to NviCandidateIndexDocument

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/model/InstanceType.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateApprovalDtoTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
I think we want to keep `InstanceType` enum when validating candidacy, so InstanceType will still be used inn `nvi-eveluator`, but it will never be stored as enum in database.
=> InstanceType from Enum to String

index-handlers/src/main/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java
Fix bug introduced by: [Index document - add type info](https://github.com/BIBSYSDEV/nva-nvi/commit/2df96ccd14c6945bae8eaaa9893e0d7746f7ccf5)
- Change `PaginatedSearchResult` type back to `NviCandidateIndexDocument`
- Add type field with static value for `NviCandidateIndexDocument`
=> Fix type info bug

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Affiliation.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Contributor.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/ContributorType.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviContributor.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviOrganization.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Organization.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/OrganizationType.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/PublicationDetails.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Today, all contributors (regardless of whether they are nvi contributors or not) with affiliations are presented under `publicationDetails` on the index document. 
It is necessary to know which of these contributors are nvi contributors, and which of these contributor affiliations are nvi affiliations in data export.
Therefore, added types `NviContributor` and `NviOrganization`, and creating these during "expansion" of contributors and affiliations.
=> Np 46085 index document contributors nvi info

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java
`UpdateIndexHandler` is failing due to openSearch serialisation error. Change data type for `modifiedDate` in index document to String
=> Change modifiedDate type to string in index document

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Approval.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Remove deprecated field `Approval` `id` from index document. Frontend has migrated to new field `institutionId`.
=> Remove deprecated field Approval id

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluatorService.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/calculator/CandidateCalculator.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/calculator/PointCalculator.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/model/VerifiedNviCreator.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/NviCandidate.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/calculator/PointCalculatorTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java
For data export, we need to know which contributor and affiliation (regardless of whether top level or sub unit) is part of the nvi reporting process for a given candidate.
Today, only the top level affiliation is peristed for nvi creators, and is not sufficient.
The nvi candidate containing nvi creators and affilitions that is persisted by `UpsertNviCandidateHandler` is constructed by `EvaluateNviCandidateHandler`.
Before:
`EvaluateNviCandidateHandler` sent creators with top level affiliations as creators of the `NviCandidate`
Changed this to:
`EvaluateNviCandidateHandler` sending creators with affiliations (regardless of whether top level or sub unit) as creators of the `NviCandidate`
(This change should not change any existing feature, only which data is persisted for creator …
=> NP-46155 Persist sub unit affiliations in stead of top level affiliations for nvi contributors

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumer.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/DeletePersistedIndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/RemoveIndexDocumentHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/PeriodStatus.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/dto/PeriodStatusDto.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateDaoTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/PeriodStatusTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
Task: Store reportedYear/ reportedPeriod for NviCandidate. 
Problem:
Not possible to add `:PERIOD#somePeriod` to hashKey or rangeKey, cause they must be equal to be able to run dynamo.getItem(UniqueKey), otherwise we have to use dynamo.query() for fetching single item which is not a good idea.
Solution:
Today we store publicationDate.year as secondary index key in dynamo. This year will also be reportedYear/period since our periods are years, like 2023. This key will be set as publicationDate.year for nvi candidates created from NVA, but set to given value for imported nvi candidates from Cristin. 
Alternative solution is to create one more secondary index, but this is not a good idea, because given implementation we have now, this new secondary index will contain the same data as …
=> Adding year to imported candidate

index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexDocumentHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, template.yaml
- Renamed subscription `NviDataEntryUpdateCandidateNotApplicableUpdateDeleteDocumentSubscription` to `NviDataEntryUpdateCandidateNotApplicableUpdateSubscription` and changed endpoint to `GenerateIndexDocumentQueue` (previously `DeletePersistedIndexDocumentQueue`)
- Create index documents also for not applicable candidates
- Add boolean `applicable` to `NviCandidateIndexDocument`
Note: Non applicable candidates will still be removed from OpenSearch due to subscription `NviDataEntryUpdateCandidateNotApplicableRemoveFromIndexSubscription`
=> Persist non applicable candidates in persisted resources.

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java
Commenting out creators from mapper and test. Not removing them, cause this extracting will be used later on.
=> commenting out creators in nvi mapper

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/ReportingPeriod.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
- Add `reportingPeriod` `year` in candidate index document
For data export, we need to know which reporting period the candidate belongs to in order to make a institution report for a given reporting year.
We could use the `publicationDate` `year` of the publication, but `reportingPeriod` `year` is more explicit. These will contain the same value in most cases.
Also, feel free to suggest better naming. Is `reportingPeriod` too similar to already implemented field `reportedPeriod`?
=> Np 45429 index document reporting period

event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/BatchScanStartHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/KeyField.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/ScanDatabaseRequest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/BatchScanStartHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/Dao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/model/KeyField.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/model/KeyFieldTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
For data migration or reindexing, it would be more effective to be able to run batch scan for specific items in the database, to avoid unnecessary "event production".
Added:
- List of enum `KeyField` `types` in `ScanDatabaseRequest`
- Modified `scanEntries` method in `CandidateRepository` to add `types` in scan request
Similar to solution implemented in publication-api: [Batch scan dao type #1357](https://github.com/BIBSYSDEV/nva-publication-api/pull/1357)
=> Np 46381 batch scan for dao type

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
- Since I implemented `reportingPeriod` in [previous PR](https://github.com/BIBSYSDEV/nva-nvi/pull/267), the year the candidate was reported is provided here
- Renamed `reportedPeriod` to `reported` and changed data type to boolean
This change will require re-indexing
(`reportedPeriod` is only consumed in data-report, I will follow up required changes here)
=> Index document: Rename reportedPeriod to reported and change data type to boolean

event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/CreateNoteRequest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Approval.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/requests/CreateNoteRequest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateNotesTest.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/CreateNoteHandler.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
Jira issue: [When a Curator adds a message to a NVI-candidate they are not set as Curator for the NVI-Candidate](https://unit.atlassian.net/browse/NP-46382)
- Set user as `assignee` if users top level org has an `Approval` for `Candidate`
- Add institutionId in `CreateNoteRequest`
=> Np 46382 Create note, set assignee if approval unassigned

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/GlobalApprovalStatus.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java
Jira issue: [Add Dispute (tvist) as enum value for global approval status](https://unit.atlassian.net/browse/NP-46476)
Global approval status value `Dispute` (også kjent som tvist) is required in data export and institution reports. See `RAPPORTSTATUS` in [instruks](https://www.cristin.no/nvi-rapportering/nvi-veiledninger/hvordan_lese_nvi-kontrolldata.html).
- If at least two institutions disagree on whether the candidate should be approved or rejected (one approved approval and one rejected approval), set `globalApprovalStatus` `Dispute` in index document.
=> NP-46476 Index document, global approval status Dispute

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java
Noticed that a lot of (applicable) `CandidateDao`s in database in test environment are missing attribute `periodYear`. Was not able to find root cause. @truhacevkir pushed [setting currect publication year when resetting candidate](https://github.com/BIBSYSDEV/nva-nvi/commit/3069c72677caafa3592b9b3fe9cc0531cc5af502).
This attribute is required to export nvi reports for institutions.
- Added code for migrating `periodYear` in `CandidateDao` if missing.
=> Migrate CandidateDao periodYear

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumer.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java
Cristin object looks like this:
Each **h_dbh_forskres_forfatter** has points for his affiliation. 
**CristinLocales** contains approvals for each topLevelOrganization. 
When crafting points, we summarize points for each **h_dbh_forskres_forfatter** at **institusjonsnr** and use topLevelOrg from CristinLocale to create institution points
```
{
"publicationIdentifier": "018dc1025afe-4a3747e4-0f53-4602-84cb-10e66a941abd",
"scientificResources": [
{
"h_dbh_forskres_forfatter": [
{
"personlopenr": "58612",
"institusjonsnr": "186",
"avdnr": "33",
"undavdnr": "81",
"gruppenr": "0"
},
{
"personlopenr": "58613",
"institusjonsnr": "186",
"avdnr": "33",
"undavdnr": "81",
"gruppenr": "0"
}
],
"kvalitetsnivakode": "2",
"arstall": "2011"
}
],
"cristinLocales": [
{
"eierkode": "UITO",
"institusjonsnr": …
```
=> summarazing point per approval institution

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluatorService.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/calculator/PointCalculator.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/model/InstitutionPoints.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/NviCandidate.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/calculator/PointServiceTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java
Jira task: NP-46529, Refactor points for affiliation calculation, persist in db.
Part 1 -> [PR Merged](https://github.com/BIBSYSDEV/nva-nvi/pull/279)
This is part 2 -> Send points for affiliation from `EvaluateNviCandidateHandler` to `UpsertNviCandidateHandler`
- Modified `NviCandidate` with list of nvi creators to contain `List<NviCreatorWithAffiliationPoints>`
- Added `List<AffiliationPoints>` in `NviCreatorWithAffiliationPoints`
In next PR: Consume and persist points for affiliation in `UpsertNviCandidateHandler`
=> Np 46529 EvaluateNviCandidateHandler: Send points for affiliation

event-handlers/src/main/java/no/sikt/nva/nvi/events/model/NviCandidate.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandlerWithLocalDynamoTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/RequeueDlqTestUtils.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/InstitutionPoints.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
To avoid loosing information about `NviCandidate` `CreatorAffiliationPoints` in case of a RequeueDLQ situation. Added test `shouldRequeueCandidateWithoutLossOfInformation`
=> Np 46529 fix creator affiliation points batch scan

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Approval.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/InstitutionPoints.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-46529, Refactor points for affiliation calculation, persist in db.
Part 1 -> https://github.com/BIBSYSDEV/nva-nvi/pull/279
Part 2 -> https://github.com/BIBSYSDEV/nva-nvi/pull/283
Part 3 -> https://github.com/BIBSYSDEV/nva-nvi/pull/287
This is the last part: add creator affiliation points in index document, so it can be used for export in data-report-api
=> Np 46529 Index document, Points for creator affiliation

event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandler.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
`ReEvaluateNviCandidatesHandler` is a tool to re-evalute and/or re-calculate points if requirements have changed in `EvaluateNviCandidatesHandler`
New case: I want to re-calculate points for all nvi canidates in database, except for the ones that are imported from cristin.
Solution: Filter out reported candidates for re-evaluation
=> ReEvaluateNviCandidatesHandler: filter out reported candidates

index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/resources/document_approved.json, index-handlers/src/test/resources/document_approved_collaboration.json, index-handlers/src/test/resources/document_assigned.json, index-handlers/src/test/resources/document_assigned_collaboration.json, index-handlers/src/test/resources/document_pending.json, index-handlers/src/test/resources/document_pending_category_degree_bachelor.json, index-handlers/src/test/resources/document_pending_collaboration.json, index-handlers/src/test/resources/document_rejected.json, index-handlers/src/test/resources/document_rejected_collaboration.json, index-handlers/src/test/resources/document_with_contributor_from_ntnu_subunit.json, index-handlers/src/test/resources/document_with_contributor_from_sikt.json, index-handlers/src/test/resources/document_with_contributor_from_sikt_but_not_creator.json, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/resources/nviCandidateContext.json, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira issue: NP-46527 Index document, supplement partOf
For aggregation purposes, modify partOf-list to only contain identifiers (not whole URI): Example:
```
"contributors": [
{
"type": "NviContributor",
"id": "https://example.org/person/997998",
"affiliations": [
{
"type": "NviOrganization",
"id": "https://example.org/organization/194.1.1.1”,
"partOf": ["194.0.0.0”, "194.1.0.0", "194.1.1.0"]
]
}
]
}
]
```
Also, updated nvi context with the following:
```
"partOf": {
"@container": "@set",
"@context": {
"@base": "__REPLACE_WITH_API_DOMAIN__/cristin/organization"
},
"@type": "@id"
}
```
This change required an update of the OpenSearch `Query` `contributorQueryIncludingSubUnits`
=> NP-46527 Index document, supplement partOf

index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/ApprovalStatus.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchAggregations.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, index-handlers/src/test/resources/document_approved.json, index-handlers/src/test/resources/document_approved_collaboration.json, index-handlers/src/test/resources/document_new.json, index-handlers/src/test/resources/document_new_collaboration.json, index-handlers/src/test/resources/document_pending.json, index-handlers/src/test/resources/document_pending_category_degree_bachelor.json, index-handlers/src/test/resources/document_pending_collaboration.json, index-handlers/src/test/resources/document_rejected.json, index-handlers/src/test/resources/document_rejected_collaboration.json, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Approval.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/model/ApprovalTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-46551 Index document, logical status `New`. This will make it easier to make aggregations for new feature: Institution report.
Same "logic" as in ticket expansion in publication-api. If approval is _pending and unassigned_, set status `New` in index document.
Updated aggregations, now no longer necessary to check if approval is assigned or not in aggregations `pending`, `pendingCollaboration`, `assigned`, `assignedCollaboration`.
=> Np 46551 Index document, approval status New

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/AggregationFormatter.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java
- Added `AggregationFormatter`
- Did not find a nice way to generically serialize all `Aggregate` variants, therefore added custom formatting for nested and string terms aggregation. Feel free to suggest better implementation here
=> Np 46528 SearchNviCandidatesHandler, format nested aggregations

index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/SearchAggregation.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/AggregationFormatter.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/AggregationFunctions.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java, index-handlers/src/test/resources/document_organization_aggregation_collaboration.json
To avoid aggregations for approvals that do not belong to requested top level org (in co-publishing cases), add a filter aggregation for top level org.
=> Np 46528 OpenSearchClient, organizationApprovalStatusAggregations: filter approvals for topLevelCristinOrg

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
`involvedOrganizations` in `Approval` (index document) should also contain top level org (`Approval.institutionId`). Aggregations are made for all uris in `involvedOrganizations`.
=> Np 46528 Index document, approval involved orgs: Add top level org

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/calculator/PointCalculator.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/model/VerifiedNviCreator.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/calculator/PointServiceTest.java
Jira task: NP-46661 Nvi point calculation: too many points for authors with more than one affiliation to one institution
- Added test `shouldCountOneInstitutionShareForCreatorsWithSeveralAffiliationsInSameInstitution`, fix counting creators for institution in `countCreators` method.
- Fixed calculation in `calculatePointsForAffiliation`: First calculate `pointsForCreator` then divide on `numberOfAffiliations` to get `pointsForAffiliation`.
=> Np 46661 Fix: Too many points for authors with more than one affiliation to one institution

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/Approval.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-46632 Aggregations for disputes
Work-around suggestion to ble able to aggregate disputes for all organizations in `involvedOrganizations` (in `Approval`s): denormalization of global approval status.
- Add `globalApprovalStatus` on all `Approval`s in index document
=> Np 46632 Index document, global approval status in approvals

index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/Approval.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/NviContributor.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/NviOrganization.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/Organization.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/OrganizationType.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java, index-handlers/src/test/resources/document_approved.json, index-handlers/src/test/resources/document_approved_collaboration.json, index-handlers/src/test/resources/document_new.json, index-handlers/src/test/resources/document_new_collaboration.json, index-handlers/src/test/resources/document_organization_aggregation_dispute.json, index-handlers/src/test/resources/document_organization_aggregation_new.json, index-handlers/src/test/resources/document_organization_aggregation_pending.json, index-handlers/src/test/resources/document_pending.json, index-handlers/src/test/resources/document_pending_category_degree_bachelor.json, index-handlers/src/test/resources/document_pending_collaboration.json, index-handlers/src/test/resources/document_rejected.json, index-handlers/src/test/resources/document_rejected_collaboration.json, index-handlers/src/test/resources/document_with_contributor_from_ntnu_subunit.json, index-handlers/src/test/resources/document_with_contributor_from_sikt.json, index-handlers/src/test/resources/document_with_contributor_from_sikt_but_not_creator.json, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/resources/nviCandidateContext.json, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-46914 _Nvi institution status aggregations missing parts of org structure_
Aggragations for institution status is made for all orgs in Index document -> `approvals.involvedOrganizations`.
Bug: `approvals.involvedOrganizations` was missing intermidiate levels.
Changes:
- Add all organizations (`contributor.affiliationId` + all orgs in `partOf`-list of the affiliation) in `approvals.involvedOrganizations`
- Make `partOf`-list contain URIs again instead of identifiers. (Mixing uris and identifiers in the model was a hassle)
- Make nvi contributors in tests affiliated to a org with two levels above in the org hierarchy to test this
=> Np 46914 Index document, involved organizations should contain all partOf levels

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/NviContributor.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/NviOrganization.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-46965 _Nvi institution report aggregations missing affiliations to top level org_
Aggragations for institution status is made for all orgs in Index document -> approvals.involvedOrganizations.
Bug: approvals.involvedOrganizations was missing top level orgs when nvi creator was affiliated directly to top level org.
Changes:
- Add top level org affiliations in `involvedOrganizations`
=> Np 46965 Fix: Nvi institution report aggregations missing affiliations to top level org

docs/openapi.yaml, index-handlers/src/main/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/OpenSearchClient.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/SearchQueryParameters.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/CandidateSearchParameters.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/OrderByFields.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/SearchResultParameters.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java
Add support for new, optional query params orderBy and sortOrder.
`orderBy`:
- Default value: createdDate
- Supported values: createdDate
`sortOrder`:
- Default value: desc 
- Supported values: desc, asc@
Handler returns 400 Bad Request if query param `orderBy` contains unsupported value
=> Np 46947 Nvi Search: query params orderBy and sortOrder

index-handlers/src/main/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandler.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FakeViewingScopeValidator.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/validator/ViewingScopeValidator.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/validator/ViewingScopeValidatorImpl.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/validator/ViewingScopeValidatorImplTest.java
Add new method `userIsAllowedToAccessOneOf` in `ViewingScopeValidator`.
A curator is allowed to view a candidate where one of the contributors affiliations is within the curators viewing scope.
This will allow following change in next PR:
```
@Override
protected void validateRequest(Void unused, RequestInfo requestInfo, Context context) throws ApiGatewayException {
var candidateIdentifier = UUID.fromString(requestInfo.getPathParameter(CANDIDATE_IDENTIFIER));
var organizations = Candidate.fetch(() -> candidateIdentifier, candidateRepository, periodRepository)
.getNviCreatorAffiliations();
if (!viewingscopeValidator.userIsAllowedToAccessOneOf(requestInfo.getUserName(), organizations)) {
throw new UnauthorizedException();
}
}
```
=> Np 47031 ViewingScopeValidator, userIsAllowedToAccessOneOf

index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/ViewingScopeHandler.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/PublicationDetails.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-rest/build.gradle, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/ViewingScopeHandler.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/CreateNoteHandler.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/NviNoteRequest.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandler.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandler.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandler.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandler.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/FakeViewingScopeValidator.java
Jira task: NP-47031 Ensure curator only see NVI candidates for their viewingScope.
Validate viewing scope in following handlers:
- `FetchNviCandidateHandler`
- `CreateNoteHandler`
- `RemoveNoteHandler`
- `UpsertAssigneeHandler`
- `UpdateNviCandidateStatusHandler`
=> Np 47031 Rest handlers, validate viewing scope

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java
Some approvals for nvi candidates are missing institution identifier, ignoring these approvals when creating candidate:
```
{
"eierkode": "KREFTREG",
"brukernavn_kontrollert": "sos",
"dato_kontrollert": "2015-10-05",
"status_kontrollert": "J"
}
```
=> not creating approval for institution missing identifier

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java
Root cause fix: https://github.com/BIBSYSDEV/nva-publication-api/pull/1753
But to make NVI indexing more robust, fetch labels from Cristin if extracting labels from index document fails
=> Index document, fetch labels from Cristin if extracting labels from index document fails

event-handlers/src/main/java/no/sikt/nva/nvi/events/QueuePersistedResourceHandler.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/QueuePersistedResourceHandlerTest.java
Noticed that `EvaluateNviCandidateHandler` was failing in cases where it was trying to evaluate if tickets where nvi candidates
Issue: Today, `QueuePersistedResourcesHandler` queues all resources published on topic `PublicationService.ExpandedEntry.Persisted` for evaluation, including tickets
Fix: Only queue publications
=> Np 46988 QueuePersistedResourcesHandler, filter out tickets and other types

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/Aggregations.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/AggregationFunctions.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/QueryFunctions.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Jira task: NP-47106 Når der er en uenighet (minst ein har avvist og minst ein har godkjent) så er det ein Tvist og dermed ikkje lenger Godkjent/Avvist.
Exclude nvi candidates with global status dispute from all status aggregations and filters
Also: Noticed a lot of duplicate methods in `AggregationFunctions` and `CandidateQuery`, so moved these to a new class, `QueryFunctions`
Ignoring one codacy issue: _Linguistics Antipattern - The method 'isNotDisputeQuery' indicates linguistically it returns a boolean, but it returns 'Query'_
=> Np 47106 Search, Exclude disputes in status aggregations and filters

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/PointService.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/resources/evaluator/candidate_academicMonograph_series_multiple_types.json
Jira issue: 
`EvaluateNVICandidateHandler` is expecting `publicationContext` `type` as String. In some cases, where there is a mismatch between NVA and Kanalregisteret on the channel type, publicationContext is array (See example).
```
{
"id": "https://api.dev.nva.aws.unit.no/publication-channels-v2/series/123/2024",
"type": [
"Series",
"Journal"
],
"identifier": "C8CCD71B-FD8B-47B4-B72A-905F6219D7D5",
"name": "Some name",
"scientificValue": "LevelOne",
"year": "2024"
}
```
Long term fix: NVA and Kanalregisteret should agree on the type of the channel
Fix short term: Revert this removal: https://github.com/BIBSYSDEV/nva-nvi/pull/277
=> Np 47379 Fix: handle multiple channel types in evaluation

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluatorService.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java
In `EvaluatorService.isPublishedBeforeOrInLatestClosedPeriod()`, a `NumberFormatException` is thrown if year is not a valid integer. Examlple: "1948-1997". 
Change:
- If `publicationDate.year` is invalid, skip evaluation and log invalid year and publication id. In this way, we can report which publications have an invalid year format and fix metadata for these if necessary
=> Np 47380 Fix: EvaluatorService, NumberFormatException

gradle/libs.versions.toml
To get latest changes in [AuthorizedBackendUriRetriever](https://github.com/BIBSYSDEV/nva-commons/commit/e637e5faea0ade289f32ea910dd3e8577997f1a0)
=> Bump nva commons to 1.40.12

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/PointService.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/resources/evaluator/candidate_academicArticle_journal_multiple_types.json
Same issue as solved in https://github.com/BIBSYSDEV/nva-nvi/pull/346, but this is for channel type `Journal` (often context of `AcademicArticle`s)
Jira issue:
`EvaluateNVICandidateHandler` is expecting `publicationContext.type` as String. In some cases, where there is a mismatch between NVA and Kanalregisteret on the channel type, publicationContext is array (See example).
```
{
"id": "https://api.dev.nva.aws.unit.no/publication-channels-v2/series/123/2024",
"type": [
"Series",
"Journal"
],
"identifier": "C8CCD71B-FD8B-47B4-B72A-905F6219D7D5",
"name": "Some name",
"scientificValue": "LevelOne",
"year": "2024"
}
```
Long term fix: NVA and Kanalregisteret should agree on the type of the channel
=> Np 47379 Fix: handle multiple journal channel types in evaluation (#346)

index-handlers/src/main/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/CandidateSearchParameters.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java
Users are experiencing Unauthorized-errors if they have a sub unit viewing scope and query parameter `affiliations` is not set when searching for nvi candidates.
Change:
- Before, search parameter affiliations was set to users top level org if query parameter `affiliations` was not provided
- Now, search parameter affiliations is set to users `viewingScope.includedUnits` if query parameter `affiliations` is not provided
- Unless you have access right `NVI_ADMIN`, then search parameter affiliations is an empty list:)
=> Np 47456 SearchNviCandidatesHandler, use viewingScope as default for search parameter affiliations

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/NviCandidateIndexDocument.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationChannel.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/model/document/PublicationChannelTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
Change in index document model: add `document.publicationDetails.publicationChannel` with `id`, `type` and `scientificValue`
Also did some refactoring in `NviIndexDocumentGenerator`: instead of getting `JsonNode expandedResource` and `Candidate candidate` as input parameters in method `generateDocument()`, added these as class variables.
=> Np 47488 IndexDocument: add publication channel id, type and scientificValue

index-handlers/build.gradle, index-handlers/src/main/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandler.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/TooManyHitsException.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/utils/MockOpenSearchUtil.java, template.yaml
Noticed only 10 candidates in report when testing `FetchInstitutionReportHandler`. 10 is the default search page size 😄 
Changes:
- Use page size (500, set in env var) and offset to fetch candidates for given year and top level organization
=> Np 47439 Institution report: Search for candidates with pagination

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/Pages.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonUtils.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/JsonUtilsTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-47490 Expand index document with page information
Extracting optional fields `begin`, `end` and `pages` from `publicationInstance` in expanded resource
Test that verifies this is `IndexDocumentHandlerTest.shouldBuildIndexDocumentAndPersistInS3WhenReceivingSqsEvent()` with `expectedIndexDocument` containing publication page info from test data setup (`expandedResource`)
=> Np 47490 Index document: Add page information

event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java
Indexing failing for candidates imported via Cristin, some of these do not have level NON_CANDIDATE, which does not seem like a valid state?
Suggestion: throw IllegalArgumentException and fix this in the data source?
=> CristinMapper: shouldThrowIllegalArgumentExceptionWhenQualityCodeIsInvalid

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
Index documents `contributor.affiliation.partOf` list for top level affiliations is containing all sub unit ids. This is a bug, a top level org is not part of any other org.
Example bug:
```
"affiliations": [
{
"type": "NviOrganization",
"id": "https://api.dev.nva.aws.unit.no/cristin/organization/185.90.0.0",
"identifier": "185.90.0.0",
"partOf": [
"https://api.dev.nva.aws.unit.no/cristin/organization/185.14.35.1",
"https://api.dev.nva.aws.unit.no/cristin/organization/185.18.0.2",
"https://api.dev.nva.aws.unit.no/cristin/organization/185.53.60.0",
"https://api.dev.nva.aws.unit.no/cristin/organization/185.35.23.0",
"https://api.dev.nva.aws.unit.no/cristin/organization/185.39.59.0",
"https://api.dev.nva.aws.unit.no/cristin/organization/185.28.5.0",
...
...
```
Expected:
```
"affiliations": …
```
=> NP-47526 Fix: Index document - top level afiiliation partOf

event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/NviCandidate.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/RequeueDlqHandlerWithLocalDynamoTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java
`ReQueueDlqHandler` failing to requeue candidates imported from Cristin missing `channelType` (`NullpointerException`)
=> ReQueueDlqHandler: Handle channel type null

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Jira task: NP-47560 Export to NVI-kontrolldata optimization: exclude non-nvi-contributors from search response
Part one:
- Index document: Extract nvi contributors (type NviContributor) in separate list
=> Np 47563 Index document: Extract nvi contributors in separate field

index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/OpenSearchClient.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/CandidateSearchParameters.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: Export to NVI-kontrolldata optimization: exclude non-nvi-contributors from search response
Change:
- Add list of excludeFields in search parameters, use this to set `SourceConfig` in search request
- In `InstitutionReportGenerator`: exclude `publicationDetails.contributors` in search request
=> Np 47564 source exclude non nvi contributors

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/Aggregations.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/QueryFunctions.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java, index-handlers/src/test/resources/document_approved_collaboration_new.json, index-handlers/src/test/resources/document_approved_collaboration_pending.json, index-handlers/src/test/resources/document_rejected_collaboration_new.json, index-handlers/src/test/resources/document_rejected_collaboration_pending.json
Jira task: NP-47460 Search aggregation "Venter på andre institusjoner" showing wrong number
Change:
- Update finalized collaboration* filters and aggregations -> Count candidates with approval status `New` as well
*`approvedCollaboration` and `rejectedCollaboration`: A candidate where requesting users top level org has approved/rejected (finalized) their `Approval`, but other institutions have not (still approval status `Pending` or `New`)
=> Np 47460 fix collaboration aggregations

index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexDocumentHandler.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
Race condition between two event flows:
1. When an _**approval is removed**_ from an applicable candidate -> We want to generate an index document with updated approvals
2. When an applicable candidate becomes not applicable and all _**approvals are removed**_ -> We want to remove the candidate from the index
Fix: In `IndexDocumentHandler` - filter non applicable candidates. This will prevent non-applicable candidates in index when approvals are removed (triggering case 1)
=> Np 47613 Fix: IndexDocumentHandler - filter non applicable candidates

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/NviCandidateIndexDocument.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Bug: `InstitutionReportGenerator` was failing when trying to generate report rows for non-applicable candidate without approvals.
In general: candidates that become non-applicable are removed from the search index, so this error should not occur. But if it does - `InstitutionReportGenerator` should handle this.
Change: If approval for institution not found for a candidate (index document), log waring and skip generation of report rows
=> Np 47613 InstitutionReportGenerator: Should not fail on appproval not found

index-handlers/build.gradle, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/utils/MockOpenSearchUtil.java
Fix bug: Not able to download report for UiO. Lambda failing due to 413-response from OpenSearch
Changes:
- Reduce the page size if OpenSearch responds with 413-error (RequestEntityTooLarge)
- The pageSize is divided by two exponentially, and the offset is adjusted according to the pageSize that was successful
- After a successful search response -> the pageSize should go back to the initial pageSize when doing the next search requests
Tested for UiO in dev ✅ 
Next step: For faster performance: I'm thinking about fetching total number of candidates for institution and year, splitting into batches and parallelising fetching this with async http client. Thoughts?
=> Np 47614 reduce pagesize on 413

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java, template.yaml
- Add sort order in search request for deterministic results
- After parallelizing fetch, reducing page size is beneficial (bigger != better:)). Page size 300 seems like the sweet spot
=> InstitutionReportGenerator: Add sort order and optimized page size

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonUtils.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/JsonUtilsTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task - Search optimizations - NP-47797 Create new trancated field(s) for contributors
Add new field, contributorsPreview, in index document. This will be used in the search response, instead of the contributors list (Ref 413-responses due to too many contributors)
- Extract `contributorsPreview` from expanded resource
- Added fallback logic in cases where expanded resource might not contain `contributorsPreview`
=> Np 47797 Index document, contributorsPreview

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonUtils.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/JsonUtilsTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-47862 Remove `contributorsPreview` from index document, use `nviContributors` for "preview" in frontend
(Almost a revert of previous commit, just keeping `contributorsCount` field)
=> Np 47798 index document remove contributors preview

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Jira task: NP-47910 Search query: hits for publicationIdentifier, title, contributor name
- Adding `publicationDetails.identifier` as new field in index document
- Making searcTerm query more specific, adding fields `identifier`, `publicationDetails.identifier`, `publicationDetails.title` and `publicationDetails.contributor.name`
=> Np 47910 Search term: hits for candidate identifier, publication identifier, title, contributor name

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/Aggregations.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/query/SearchAggregation.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Jira task: NP-47595 Search optimizations, remove organizationApprovalStatuses -aggregation from default aggregations
`organizationApprovalStatuses`-aggregations is a heavier aggregation, and is not necessary as a default aggregation
Also, when we merge https://github.com/BIBSYSDEV/nva-nvi/pull/390 (increase size limit for terms aggregations), this will affect performance more
=> Remove organizationApprovalStatuses from default aggregations

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Jira task: NP-47927 Search for unique identifiers should only give one hit
Thanks for the help @StigNorland 😄 
- Modify mulitimatch query, add operator `And` and type `CrossFields`
=> Np 47927 One search hit for unique identifiers

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/CandidateSearchParameters.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java
Jira task: NP-47798 Nvi Search: Remove contributors-list from search response
After frontend has migrated to fields `nviContributors` and `contributorsCount`, remove contributors-list from search response. This is to reduce the response size on "monsterposter" 😄 
`OpenSearchClient` is mocked in `SearchNviCandidatesHandlerTest`
There is a test in `OpenSearchClientTest` verifying that this functionality works, see `shouldExcludeFields()`
=> Np 47798 Remove contributors-list from search response

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluatorService.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/model/NviCandidate.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/InstanceType.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/requests/UpsertCandidateRequest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateRepositoryTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateApprovalDtoTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/model/InstanceTypeTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/ExceptionMapperTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
Jira task: NP-48030 NVI missing validation of instance type
- Change `instanceType` `type` in evaluated `NviCandidate` and  `UpsertCandidateRequest` to `InstanceType` (enum)
- Keeping `Candidate.publicationDetails.type` and `DbCandidate.instanceType` `String`s because these also represent imported candidates from Cristin, which may include other unknown instance types
=> Use enum InstanceType in evaluated candidate and upsert request

event-handlers/src/main/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandler.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateRepositoryTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateApprovalDtoTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateNotesTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
Jira task: NP-48035 - CloudWath Alarm: NVI Persisting candidate failed
Due to:
```
java.lang.NullPointerException: Cannot invoke \"no.sikt.nva.nvi.common.db.CandidateDao.identifier()\" because \"candidateDao\" is null\n\t
at no.sikt.nva.nvi.common.service.model.Candidate.createCandidate(Candidate.java:441)\n\tat 
no.sikt.nva.nvi.common.service.model.Candidate.upsert(Candidate.java:141)\n\tat 
...
```
Anlalysis: Persisting the candidate has not _actually_ failed, but _fetching_ the candidate immediately after creating it in some very few cases returns `null`. I think this is due to the eventual consistency model of DynamoDB.
Discussed following alternatives with @LarsV123:
1. Use `GetItemEnhancedRequest` with `consistentRead` set to `true` when fetching the candidate immediately after …
=> Np 48035 Candidate.upsert() void

buildSrc/src/main/groovy/nva.nvi.java-conventions.gradle, config/pmd/ruleset.xml, index-handlers/src/main/java/no/sikt/nva/nvi/index/query/Aggregations.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java, index-handlers/src/test/resources/document_organization_aggregation_rejected.json
Jira task: NP-48157 Institution Status Report: Aggregated points should not contain rejected points
Change:
- Filter out rejected approvals when aggregating total points in `organizationApprovalStatusAggregation`
- (Yes, this is a breaking change for FE, coordinating deplyoment with FE)
- Updated to pmd 7.8.0. See release notes, [fixed issues](https://github.com/pmd/pmd/releases#fixed-issues)
=> Np 48157 Aggregation organizationApprovalStatuses should not contain rejected points

event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Approval.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/PublicationChannel.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/PublicationDetails.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java
Jira task: NP-48112 Update reset-requirements for approved/rejected candidate
Changes in `shouldResetCandidate()` checks:
- Reset if publication channel `id` is updated
- Reset if creator `id`s (not affiliations) are updated
- Do not reset if creator affiliation changes within same top level organization
Next step/PR: Do not reset if creator is identified (no `id` -> `id`) without affiliation changes
=> Np 48112 Do not reset candidate approvals on creator sub unit affiliation change

event-handlers/src/test/java/no/sikt/nva/nvi/events/QueuePersistedResourceHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/PeriodStatusTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateApprovalTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/model/InstanceTypeTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java
Add names to parameterized tests so that the GitHub test results bot can differentiate between new and old tests (no name => automatically generated name for each test run => bot thinks the test was replaced).
=> refactor: Add names to parameterized tests

nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/ReportStatusDto.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchReportStatusByPublicationIdHandlerTest.java
FE noticed that it is also relevant to know whether all approvals are approved in an open period, so added two new statuses that can be returned by `FetchReportStatusByPublicationIdHandler`
=> Np 48263 FetchReportStatusByPublicationIdHandler - Global status APPROVED and REJECTED

template.yaml
This is done purely to trick CFN into recreating the resource, as the stack is stuck in an invalid state.
=> refactor: Rename handler to force recreation of resource

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/CreatePeriodRequest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/UpdatePeriodRequest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/Validator.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateApprovalTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/model/NviPeriodTest.java
Ticket: https://sikt.atlassian.net/browse/NP-48396
This allows creating/updating NVI periods with date in the past.
This validation should be expanded and improved in future (see [NP-48230](https://sikt.atlassian.net/browse/NP-48230)), but for now we can allow creating NVI periods start/ending in the past.
[NP-48230]: https://sikt.atlassian.net/browse/NP-48230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Remove incorrect validation on NviPeriod upsert

event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/dto/ContributorDto.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/dto/ContributorDtoTest.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexDocumentHandler.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/Dao.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/DynamoEntryWithRangeKey.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/model/DbCreatorTypeListConverter.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/DynamoDbUtils.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/DynamoDbUtilsTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandlerTest.java
This is intended to fix an issue with parsing `CandidateDao` after changes to the data model, by replacing the object mapper used throughout the project. The `dynamoObjectMapper` used previously ignored empty fields (i.e. null values), which I believe caused issues with parsing certain values.
=> fix: Replace objectMapper

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/InstitutionPoints.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/model/InstitutionPointsTest.java
This adds validation logic to handle cases where the list of points for a creator with no points is stored in DynamoDB as `null` instead of an empty list.
=> fix: Parse null as empty list

index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Replace Thread.sleep in OpenSearch container tests with a forced refresh operation on indices to improve test speed.
Local testing indicates that this improves the execution time of this test suite from 2 minutes 37 seconds to 7 seconds.
=> perf: Replace sleep with force-refresh to improve test speed

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/NviStatusRequest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java
Removes the `candidateId` from the request, as this is taken from path parameters and the update request applied directly to the `Candidate`. A previous PR added validation on this field, which causes errors as the field is not actually in use.
Also adds an empty `allowedOperations` field to the now-deprecated builder, to ensure the field is always present (as the OpenAPI spec promises).
=> fix: Remove unused identifier from NviStatusRequest

nvi-rest/src/test/java/no/sikt/nva/nvi/rest/BaseCandidateRestHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
Ticket: https://sikt.atlassian.net/browse/NP-48561
This refactors the REST handler tests to all extend the same base class, in a separate PR from the actual business logic changes.
=> [np-48561] refactor: Extend base class in all REST handler tests

nvi-rest/src/main/java/no/sikt/nva/nvi/rest/model/User.java, nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandler.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java
Ticket: https://sikt.atlassian.net/browse/NP-48561
This PR refactors access control in `UpsertAssigneeHandler` to use `identityServiceClient` instead of manually performing the same call. It is done in conjunction with this ticket to simplify testing of other necessary changes in the handler.
The authorization check in this handler is slightly more complex because we check the access level of the user being assigned and not just the user making the request.
=> [np-48561] refactor: Use identity service in UpsertAssigneeHandler

event-handlers/build.gradle, index-handlers/build.gradle, nvi-commons/build.gradle, nvi-commons/src/test/java/no/sikt/nva/nvi/common/client/OrganizationRetrieverTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/model/OrganizationTest.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/model/OrganizationFixtures.java, nvi-rest/build.gradle, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/BaseCandidateRestHandlerTest.java
This is a proof of concept and initial framework for using `textFixtures`, with the goal of moving shared test utility code to the `nvi-commons` module. This adds an example `OrganizationFixture` with copies of existing utility methods to show that imports work properly.
=> build: Add support for textFixtures in nvi-commons

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/PublicationDetails.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/RequestUtil.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateApprovalTest.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/TestScenario.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/UpsertRequestBuilder.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/model/OrganizationFixtures.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandlerTest.java
Ticket: https://sikt.atlassian.net/browse/NP-48242
Rewrites update logic for `Candidate` to handle cases where only some approvals should be reset and not all of them, i.e. when a contributor has their identity verified.
=> [np-48242] fix: Handle approval reset on identified creator

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/Approval.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentTestUtils.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java
Ticket: https://sikt.atlassian.net/browse/NP-48641
Fixes issues with generating Excel reports from index documents with unverified creators by mapping missing values to zero.
This scenario should possibly be prevented before the documents are created, but that would require a full re-indexing and more work.
=> [np-48641] fix: Handle candidates without verified creators

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/QueryFunctions.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentTestUtils.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java, index-handlers/src/test/resources/document_approved.json, index-handlers/src/test/resources/document_approved_collaboration_new.json, index-handlers/src/test/resources/document_approved_collaboration_pending.json, index-handlers/src/test/resources/document_dispute_not_sikt.json, index-handlers/src/test/resources/document_new.json, index-handlers/src/test/resources/document_new_collaboration.json, index-handlers/src/test/resources/document_organization_aggregation_collaboration.json, index-handlers/src/test/resources/document_organization_aggregation_dispute.json, index-handlers/src/test/resources/document_organization_aggregation_new.json, index-handlers/src/test/resources/document_organization_aggregation_pending.json, index-handlers/src/test/resources/document_organization_aggregation_rejected.json, index-handlers/src/test/resources/document_pending.json, index-handlers/src/test/resources/document_pending_category_degree_bachelor.json, index-handlers/src/test/resources/document_pending_collaboration.json, index-handlers/src/test/resources/document_rejected.json, index-handlers/src/test/resources/document_rejected_collaboration_new.json, index-handlers/src/test/resources/document_rejected_collaboration_pending.json, index-handlers/src/test/resources/document_with_contributor_from_ntnu_subunit.json, index-handlers/src/test/resources/document_with_contributor_from_ntnu_toplevel.json, index-handlers/src/test/resources/document_with_contributor_from_sikt.json
Ticket: https://sikt.atlassian.net/browse/NP-48710
This changes candidate search to filter by reporting period year instead of publication year.
These should be identical, but some existing data has a mismatch between these fields which caused the candidate to show up for the wrong year in the curator workflow.
=> [np-48710] fix: Use year param in search

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Ticket: https://sikt.atlassian.net/browse/NP-48731
Adds the field `publicationDetails.nviContributors.name` to search queries in order to allow full-text search on these names.
Note that this field is already mapped separately from `publicationDetails.contributors.name` (which is only searchable as a keyword), apparently as an optimization to handle publications with many irrelevant contributors.
=> [np-48731] fix: Allow text search for NviContributors

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluatorService.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/PointService.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/model/PublicationChannel.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluationTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonUtils.java, nvi-commons/src/main/resources/publication_query.sparql, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/JsonUtilsTest.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/SampleExpandedPublicationChannel.java
Ticket: https://sikt.atlassian.net/browse/NP-48689
This refactors `PointService` to use `PublicationDto` instead of re-creating the necessary data using `JsonNode` and extra networks calls. This in effect eliminates network calls checking for top-level organizations of Contributors during the evaluation stage. Note that we still check the NVI status of top-level organizations here and that the old logic is duplicated in the indexing stage, which must be addressed separately.
It also fixes a bug in the "is this an international collaboration" part of the SPARQL query, as this did not previously check that the affiliation was for a `Creator`.
This PR shrinks `PointService` to the point that it perhaps does not make sense to keep it as a separate "service class", but it is left for now to …
=> [np-48689] perf: Simplify PointService

event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateWithSyntheticDataTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/dto/ContributorDto.java, nvi-commons/src/main/resources/publication_query.sparql, nvi-commons/src/test/java/no/sikt/nva/nvi/common/dto/ContributorDtoTest.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/examples/ExamplePublications.java
Ticket: https://sikt.atlassian.net/browse/NP-49197
Adds handling of documents where the same contributors is listed multiple times with different roles.
For simplicity, this is done by discarding all contributors that are not creators, as they are irrelevant here.
If non-creator contributors become relevant, we will have to handle this differently.
=> [np-49197] fix: Handle contributors with multiple roles

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/PublicationDetails.java
Fixes null-pointer exceptions on records that are not migrated yet.
=> fix: Use null-check for migrated fields

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java
When migrating nvi candidates from Cristin, we use CristinLocales to construct approvals. It shows up that nvi candidate in Cristin can contain multiple "approvals" pointing to the same institution. Removing those duplicates when importing them, as today they are failing on condition when persisting to database, cause institutionId for approval is primary key in DynamoDB. 
`Transaction request cannot include multiple operations on one item (Service: DynamoDb, Status Code: 400, Request ID: VOQHVFCPJ25L4D77N1SU5LTF4BVV4KQNSO5AEMVJF66Q9ASUAAJG) (SDK Attempt Count: 1)`
=> removing approvals for the same institution when migrating nvi candidates from Cristin

event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateApprovalTest.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/model/PublicationDateFixtures.java, nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchReportStatusByPublicationIdHandlerTest.java
Ticket: https://sikt.atlassian.net/browse/NP-49257
This is initial refactoring to simplify work on the issue and not a solution for it.
Changes:
- fix: Use non-random year in flaky tests
- refactor: Remove deprecated `updateApproval` method that is no longer needed
=> [np-49257] refactor: Remove deprecated method and fix flaky test

event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateWithSyntheticDataTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/exceptions/ParsingException.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/PublicationLoaderService.java
Changes:
- Adds a custom `ParsingException` to get rid of linter complaints about throwing `RuntimeException`
- Refactors `PublicationLoaderService` in order to log relevant data when it fails
- Expands existing logging in `PublicationLoaderService` to make it easier to see the root cause. Note that the raw JSON-LD output of the SPARQL query is logged if we fail to convert it to a `PublicationDto` (which is a common issue).
=> refactor: Expand logging in PublicationLoaderService for debugging

event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/BatchScanRecoveryHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/RecoveryEvent.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/BatchScanRecoveryHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/BatchScanUtil.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/BatchScanUtilTest.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/EnvironmentFixtures.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/queue/FakeSqsClient.java, template.yaml
Ticket: https://sikt.atlassian.net/browse/NP-49358
This sets up a handler to process failed messages from BatchScan in batches. When BatchScan fails to process a record, it skips the record and throws it to a DLQ which this new handler consumes (after being manually triggered).
=> batch scan recovery handler

event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/BatchScanRecoveryHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandlerTest.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java, index-handlers/build.gradle, index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/model/DbPublicationDetails.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/BatchScanUtil.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/Validator.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java, nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/BatchScanUtilTest.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/EnvironmentFixtures.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/TestScenario.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/UpsertRequestBuilder.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/db/CandidateDaoFixtures.java, nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/db/DbPublicationDetailsFixtures.java, nvi-test/src/main/java/no/sikt/nva/nvi/test/SampleExpandedPublication.java, template.yaml
Ticket: https://sikt.atlassian.net/browse/NP-49367
Changes:
- fix: Rewrites the temporary migration code in `BatchScanUtil` so that it should handle both:
- Existing candidates with data we want to restructure
- Existing candidates imported previously with missing data
- refactor: Set up minimal data required for existing tests in fake S3
=> [np-49367] fix: Migrate data for existing imported candidates in BatchScan

event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/BatchScanRecoveryHandler.java, event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandler.java, event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/BatchScanRecoveryHandlerTest.java, nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/BatchScanUtil.java
Changes:
- refactor: Remove duplicate test method
- chore: Add more logging to handlers in order to debug failing candidates
=> refactor: Add more logging to BatchScan/Recovery handlers

docs/openapi.yaml
Ticket: https://sikt.atlassian.net/browse/NP-49331
Changes:
- Adds query parameters to OpenAPI spec for planned changes:
- `status`: Filter by one of multiple approval status for current user organization
- `globalStatus`: Filter by one of multiple global approval statuses
- `excludeUnassigned`: Exclude candidates with no assigned curator.
- `filter`: Three new special filters that replace the existing "filters". These cover special requirements that cannot be combined with each other.
- Removes current `filter` options from OpenAPI spec. The endpoint still supports them, but they will be removed when the planned changes are implemented and the frontend switches over.
- Fixes various typos and minor errors in the existing OpenAPI spec
- Improves examples and validation of existing OpenAPI …
=> [np-49331] docs: Add OpenAPI for planned changes

nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/BatchScanUtil.java
Ticket: https://sikt.atlassian.net/browse/NP-49384
Changes:
- refactor: Add full stacktrace to errors during batch scan
- fix: Handle publications with no affiliated organizations (i.e. `NullPointerException`)
=> fix: Handle publications with no affiliated organizations

template.yaml
Ticket: https://sikt.atlassian.net/browse/NP-49439
This increases the timeout for the `CristinNviEventConsumer` lambda to match the existing `EvaluateNVICandidateHandler` lambda. These both need the same high timeout to handle rare cases with large documents.
=> fix: Increase lambda timeout

event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateWithSyntheticDataTest.java
The current test (5k contributors in 45 seconds) occasionally fails during CI builds. The actual requirement is more generous (10k in 300 seconds), so we can adjust this a bit to limit the flakiness.
=> test: Adjust test timeout to limit flaky builds

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/query/QueryFilterType.java, index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java, index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
Ticket: https://sikt.atlassian.net/browse/NP-49371
This is incidental refactoring to remove linter warnings and make the structure easier to parse.
Changes:
- refactor: Convert `CandidateQuery` to a record and remove the duplicate inner class for parameters
- refactor: Extract the enum `QueryFilterType` to a separate file
- refactor: Combine relevant parameters into a single `ApprovalQuery` record in the builder instead of passing them through one by one
=> [np-49381] refactor: Simplify file structure

build-logic/build.gradle, build-logic/settings.gradle, build-logic/src/main/groovy/nva.nvi.java-conventions.gradle, build.gradle, event-handlers/build.gradle, gradle.properties, gradle/libs.versions.toml, index-handlers/build.gradle, integration-tests/build.gradle, nvi-commons/build.gradle, nvi-rest/build.gradle, nvi-test/build.gradle, settings.gradle
Changes:
- refactor: Move version number for `nva-commons` to `gradle.properties` in order to reference it during build
- feat: Use version catalog from `nva-commons` for most dependencies
- build: Bump `nva-commons` to `2.3.5`
Note that more of the remaining dependencies and plugins can be taken from `nva-commons` when recent changes there are published. Because of this, I'm not cleaning up the mixed casing in `libs.versions.toml` here.
=> feat: Use shared version catalog

build-logic/src/main/groovy/nva.nvi.root-module-conventions.gradle, gradle.properties
Enables configuration cache
- Necessarily moves a few lines of code to avoid calls to gradle scripting from inside closures
=> Enable configuration cache

buildspec.yaml, gradle.properties, nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/NviCreator.java, sam-build.sh
Workaround to enable Gradle configuration cache for local development, while keeping it disabled for `sam build` (which does not support it yet).
Changes:
- build: Enable Gradle configuration cache by default
- ci: Disable Gradle configuration cache for CodeBuild
- feat: Add a wrapper script for running `sam build` locally with options
=> build: Enable Gradle configuration cache for local development
