BIBSYSDEV/nva-nvi

index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexNviCandidateHandler.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/OpenSearchIndexClient.java

Is it for debugging? If yes, remember to remove them

Logging env variables for debugging

---

buildSrc/src/main/groovy/nva.nvi.java-conventions.gradle
index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandler.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/OpenSearchClient.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/SearchClient.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Affiliation.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/ApprovalStatus.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/SearchResponseDto.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexNviCandidateHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java
index-handlers/src/test/resources/document_approved.json
index-handlers/src/test/resources/document_pending.json
index-handlers/src/test/resources/document_rejected.json

We get following aggregations:
```
{
"approvalStatus.rejected": {
"docCount": 1
},
"approvalStatus.pending": {
"docCount": 2
},
"approvalStatus.approved": {
"docCount": 1
}
}
```

Np 44997 facet for approval status

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/ApprovalStatus.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/Candidate.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/Institution.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/ReportingStatus.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/VerifiedCreator.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/CandidateTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/ReportingStatusTest.java

I was missing verifiedCreators in the data model when i started implemtenting UpsertNviCandidateHandler.
Changes:
- Made Institution its own record
- Added VerifiedCreator

VerifiedCreator

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/Username.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/ApprovalStatus.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Candidate.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/CompletionStatus.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Institution.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Level.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Note.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Period.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/ReportingStatus.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Status.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Username.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/VerifiedCreator.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/CandidateTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/ReportingStatusTest.java

Added publicationDate in Candidate. It's a String in publication-api, and therefore here as well. It can have different formats, for example "2023" og "2023-01-01"

Added publicationDate in Candidate.java

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Candidate.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Creator.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Period.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/CandidateTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/ReportingStatusTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java

Changes after refinement discussions yesterday:
- Removed period from Candidate
- Added publication bucketUri to Candidate
- Added start date and end date to Period

Data model updates

---

event-handlers/src/main/java/events/UpsertNviCandidateHandler.java
event-handlers/src/test/java/events/FakeNviCandidateRepository.java
event-handlers/src/test/java/events/UpsertNviCandidateHandlerTest.java
template.yaml

Fix template for UpsertNviCandidateHandler. Fix EndpointConfiguration type

Fixes in template

---

event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/NviCandidateRepository.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/ApprovalStatus.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Candidate.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/events/CandidateEvaluatedMessage.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/CandidateTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/NviCandidateRepositoryTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
nvi-rest/build.gradle
nvi-rest/src/test/java/no/sikt/nva/nvi/fetch/FetchNviCandidateHandlerTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java

Added `points` field in `Candidate`. Persists points with Candidate in NviService

Persist candidate points

---

event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/Candidate.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/business/InstitutionPoints.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/CandidateTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
nvi-rest/src/main/java/no/sikt/nva/nvi/fetch/FetchCandidateResponse.java
nvi-rest/src/main/java/no/sikt/nva/nvi/fetch/InstitutionPoints.java
nvi-rest/src/test/java/no/sikt/nva/nvi/fetch/FetchNviCandidateHandlerTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java

Change institution points from Map to Object when persisting and exposing.
Plan for migration in DB: delete all candidates in DB and start over with persistence and indexing:)

InstitutionPoints refactor

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandler.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java

Require non null for publicationDetails fields in CandidateEvaluatedMessage

Require non null for publicationDetails fields in CandidateEvaluatedMessage

---

event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
nvi-rest/build.gradle
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/ApprovalStatus.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchCandidateResponse.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/InstitutionPoints.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/Note.java
nvi-rest/src/test/java/no/sikt/nva/nvi/fetch/FetchNviCandidateHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/CreateNviPeriodHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/UpdateNviPeriodHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandlerTest.java
template.yaml

Have moved fetch directory in nvi-rest to nvi-rest/rest/fetch instead of nvi-rest/fetch

Period handlers update

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/UpdateIndexHandler.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java

- Updated tests in UpdateIndexHandlerTest (fixing failing build)
- Added document identifier in logging

Log document identifier in UpdateIndexHandler

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/utils/ExpandedResourceGenerator.java
index-handlers/src/test/resources/genericDynamoDbRecord.json

shouldAddDocumentToIndexWhenNviCandidateExistsInResourcesStorageWithDifferentDateFormats

Handle different date formats

---

nvi-rest/src/main/java/no/sikt/nva/nvi/CandidateResponse.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/CreateNoteHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/NviNoteRequest.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/Note.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java

Requested change by frontend: CandidateResponse Note user type changed to String
Also fixed bug: Fixed NviNoteRequest variable name according to open api docs (note -> text)

CandidateResponse Note user type changed to String

---

nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/CreateNoteHandler.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java

Require field text in NviNoteRequest. Test: shouldReturnBadRequestIfCreateNoteRequestInValid

Validate create note request

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java

Change points scale to four when indexing candidate

Change points scale to four when indexing candidate

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/model/DbApprovalStatus.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java

Bug reported by frontend: Rejection reason should be removed when status updated from Rejected -> Pending and Approved -> Pending.

Fix approval status approved after rejected

---

nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandlerTest.java

Replace CandidateResponse with CandidateDto

Replace CandidateResponse with CandidateDto

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/BatchScanStartHandler.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandler.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/model/ScanDatabaseRequest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/BatchScanStartHandlerTest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/EventBasedBatchScanHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/DynamoEntryWithRangeKey.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/NviPeriodDao.java

Suggestions

---

nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/utils/ExceptionMapper.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandlerTest.java

- Check if user har access right MANAGE_NVI_CANDIDATES
- Check if users top level org has any approvals for requested candidate

Np 45459 fetch candidate access control

---

docs/openapi.yaml
index-handlers/src/main/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandler.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/CandidateQuery.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/CandidateSearchParameters.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java
index-handlers/src/test/resources/document_pending_category_degree_bachelor.json

Adding search by title to NVI candidates. Results give partial matches.

Adding search by title to NVI candidates.

---

event-handlers/build.gradle
event-handlers/src/main/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandler.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java
index-handlers/build.gradle
template.yaml

If error occurs:
- Send message to DLQ with publicationId and exception message
- Log error

Np 45472 UpsertNviCandidateHandler dlq

---

docs/openapi.yaml
index-handlers/src/main/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandler.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/CandidateQuery.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/CandidateSearchParameters.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java

Adding contributor and assignee filter params in NVI candidates search

Adding contributor and assignee filter params in NVI candidates search.

---

nvi-commons/src/main/resources/sparql/nvi.sparql
nvi-evaluator/src/main/java/no/sikt/nva/nvi/evaluator/calculator/PointCalculator.java
nvi-evaluator/src/test/java/no/sikt/nva/nvi/evaluator/EvaluateNviCandidateHandlerTest.java

- Add json alias scientificValue to handle publication channel v2 model
- Modify nvi sparql to handle both level and scientificValue

Publication channels v2 - scientificValue

---

docs/openapi.yaml
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandler.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandlerTest.java
template.yaml

Fetch candidate by publicationId

Np 45466 fetch candidate by publication

---

event-handlers/src/test/java/no/sikt/nva/nvi/events/UpsertNviCandidateHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/CandidateBO.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/dto/CandidateDto.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateBOTest.java

Remove undistributed points from CandidateDto

Remove undistributed points from CandidateDto

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Note.java

Refactor: Remove NoteDao from BO Note

Refactor: Remove NoteDao from BO Note

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/model/ReEvaluateRequest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandlerTest.java

Fix bug: ReEvaluateRequest must contain detail type

Fix bug: ReEvaluateRequest must contain detail type

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandler.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DynamoDbEventToQueueHandler.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DynamoDbUtils.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/db/ExceptionUtils.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/DynamoDbTestUtils.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/QueueServiceTestUtils.java
template.yaml

DataEntryUpdateHandler: send messages to dlq when handling failure

Np 45509 DataEntryUpdateHandler DLQ

---

nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServiceTest.java
template.yaml

DLQs for unexpected errors

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandler.java
index-handlers/build.gradle
index-handlers/src/main/java/no/sikt/nva/nvi/index/IndexDocumentHandler.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/UpdateIndexHandlerV2.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerV2Test.java
template.yaml

Send messages to dlq when handling failure

Np 45509 UpdateIndexHandlerV2, IndexDocumentHandler: DLQ

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java

Jira task: [Remove unnecessary organization requests](https://unit.atlassian.net/browse/NP-45521)
Only adding partOf-list for affiliations of contributors that are nvi creators to reduce time spent on http-requests that are not necessary for the index document.

Np 45521 index document org requests

---

index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/client/OrganizationRetriever.java

Use cristin proxy version=2023-05-26 in `OrganizationRetriever`

Use cristin proxy version=2023-05-26

---

template.yaml

Remove SnapStart for `DeleteNviCandidateIndexHandler`, not necessary. Add AutoPublishAlias: live

Remove SnapStart for DeleteNviCandidateIndexHandler

---

docs/openapi.yaml
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/main/resources/nviCandidateContext.json
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateContextHandler.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateContextHandlerTest.java
template.yaml

Followed same design as in publication-api. Endpoint for fetching nvi context. First version.

FetchNviCandidateContextHandler

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinLocale.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReport.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumer.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/EventReferenceWithContent.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java
template.yaml

Fikser bygget og legger til lesing av nvi-report fra s3

Fixing bug

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java

- Add `createdDate` and `modifiedDate` on creation
- Update `modifiedDate` on update

Add createdDate and modifiedDate to Candidate

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java

To be used in report-api to fetch candidates modified within a given time range.

Add modifiedDate to index document

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandler.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Affiliation.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Approval.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/Contributor.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java
index-handlers/src/test/resources/document_approved.json
index-handlers/src/test/resources/document_approved_collaboration.json
index-handlers/src/test/resources/document_assigned.json
index-handlers/src/test/resources/document_assigned_collaboration.json
index-handlers/src/test/resources/document_pending.json
index-handlers/src/test/resources/document_pending_category_degree_bachelor.json
index-handlers/src/test/resources/document_pending_collaboration.json
index-handlers/src/test/resources/document_rejected.json
index-handlers/src/test/resources/document_rejected_collaboration.json
index-handlers/src/test/resources/document_with_contributor_from_ntnu_subunit.json
index-handlers/src/test/resources/document_with_contributor_from_ntnu_toplevel.json
index-handlers/src/test/resources/document_with_contributor_from_sikt.json
index-handlers/src/test/resources/document_with_contributor_from_sikt_but_not_creator.json
nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java

Add type info for `NviCandidate`, `Contributor`, `Approval` and `Affiliation`.

Index document - add type info

---

nvi-commons/src/main/resources/nviCandidateContext.json

Add institutionId type to context

Add institutionId type to context

---

docs/openapi.yaml
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/db/DataEntryUpdateHandlerTest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/NviPeriodDao.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/PeriodRepository.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/PeriodStatus.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/NviService.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/dto/ApprovalDto.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/dto/CandidateDto.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/dto/PeriodStatusDto.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/exception/PeriodNotFoundException.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/ExceptionMapper.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/NviServicePeriodTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/dto/CandidateDtoTest.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviPeriodHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/model/NviPeriodDto.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/CreateNviPeriodHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/UpdateNviPeriodHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviPeriodHandlerTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
template.yaml

- Added open fetchPeriod endpoint. 
- Have added id to NviPeriod, NviPeriodDto, ReportStatus and ReportStatusDto.
- Renamed `periodStatus` on CandidateDto and Candidate to `period`.
- Renamed `reportStatus` on CandidateDto and Candidate to `status`.

adding id to period and implementing fetch period endpoint

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java

Crafting period for candidate fetched by publicationId in the same way as for candidate fetched by id.

crafting period id when fetching by publicationId

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinConversionException.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinEventConsumerException.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinLocale.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReport.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumer.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinUser.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/ErrorReport.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/ScientificPerson.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/ScientificResource.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java

Vi bør vurdere å implementere lagring av feilmeldinger, på samme måte som under cristin-importen.

Mapping new cristin data to nvi candidate

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java

Assignees kan mangle i følge Terje

throwing exception when missing DbLevel

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java

CandidateDao missed those:
.periodYear(periodYear)
.version(version);

Attempting to fix period

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/dto/CandidateDtoTest.java

Added following fields to index document:
- `globalApprovalStatus`
- `reportedPeriod`
- `publicationTypeChannelLevelPoints`
- `creatorShareCount`
Adding `internationalCollaborationFactor` in following PR, might be a bigger change (depending on implementation choice)

Np 46247 Index document: More data relevant for reporting.

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/NviCandidateIndexDocument.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java

Added `internationalCollaborationFactor` to index document. Required for reporting.

Added internationalCollaborationFactor to index document

---

nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchReportHandler.java
template.yaml

Add support for BinaryMediaType application/vnd.openxmlformats-officedocument.spreadsheetml.sheet for ScientificIndexApi

FetchDataReportHandler: Support .xlsx

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReport.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/ScientificPerson.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java

Utvider modellen, beregner poeng i en annen pr.

adding more fields to report

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java

Extracting channelId.
These test are ugly, but they show expected input and output. In addition they are there till we have migrated Cristin to NVA, so I think it's great.

extracting channel id

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumer.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java

Never writing to database candidates missing reportedYear

attempting to fix missing repotedyear

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateDao.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java

Remove migration code for createdDate, modifiedDate and instanceType

Remove migration code for createdDate, modifiedDate and instanceType

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/CristinMapper.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/cristin/InstitutionPoints.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinMapperTest.java

Mapping creatorPoints, this collector is ugly, but it does everything in a single stream.

mapping creator affiliation points

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/SearchNviCandidatesHandlerTest.java

shouldReturnPaginatedSearchResultWithAggregationTypeInIdIfGiven

Np 46528 SearchNviCandidatesHandler: Search result id, aggregationType

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java

Flip `statusAggregation` and `organizationAggregation`. Add statusAggregation as aggregation in organizationAggregation

OpenSearchClient, organizationApprovalStatusAggregations: flip statusAggregation and organizationAggregation

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/AggregationFunctions.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java
index-handlers/src/test/resources/document_organization_aggregation_collaboration.json
index-handlers/src/test/resources/document_organization_aggregation_new.json
index-handlers/src/test/resources/document_organization_aggregation_pending.json

SumAggregate of points for all involved organizations

Np NP-46633 OpenSearchClient, organizationApprovalStatusAggregations: add points aggregation

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandler.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluatorService.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/model/NviCandidate.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateWithCristinDataTest.java
event-handlers/src/test/resources/evaluator/candidate_academicArticle.json
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/create/CreateNoteHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandlerTest.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandlerTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java

Jira task: NP-46826 Handle reported candidates
- New check in `EvaluatorService`: if candidate exists and belongs to closed period -> skip evaluation.
- Moved logging to `EvaluatorService`

Np 46827 Evaluator, filter existing candidates in closed periods

---

gradle/libs.versions.toml
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandler.java
nvi-rest/src/test/java/no/sikt/nva/nvi/rest/fetch/FetchNviPeriodsHandlerTest.java
nvi-rest/src/test/resources/userResponseBodyWithAccessRight.json
nvi-rest/src/test/resources/userResponseBodyWithoutAccessRight.json

ApiGatewayHandler i nva = { strictly = '1.39.3' } kommer nå med to ekstra security headers. Resten av dependenciene er kun bumping for å få det til å fungere.

NP-46878-security-headers

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/Aggregations.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/CandidateQuery.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/model/search/SearchAggregation.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java
index-handlers/src/test/resources/document_dispute_not_sikt.json

- Support for query param `filter` = `dispute`
- Add aggregation `dispute` in aggregations returned

Np 46944 Nvi search, Add filter and aggregations for disputed candidates

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/NviCandidateIndexDocument.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/OpenSearchClientTest.java

Add createdDate to index document. To support ordering by `createdDate`

Np 46947 Index document, add created date

---

gradle/libs.versions.toml
index-handlers/src/main/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionStatusAggregationHandler.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/CreateNoteHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/create/CreateNviPeriodHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateByPublicationIdHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateContextHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviCandidateHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviPeriodHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/fetch/FetchNviPeriodsHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/remove/RemoveNoteHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpdateNviCandidateStatusHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpdateNviPeriodHandler.java
nvi-rest/src/main/java/no/sikt/nva/nvi/rest/upsert/UpsertAssigneeHandler.java

Update commons to 1.40.2. Implement validation methods

Update commons to 1.40.2. Implement validation methods

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/calculator/CreatorVerificationUtil.java

Gives more correct information during debugging

CreatorVerificationUtil, log customerApiUri

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java

Not receiving expected number of candidates when testing this endpoint for institutions in dev. Log number og search hits

InstitutionReportGenerator: log search hits

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java

Jira task: NP-47491 Expand index document with language

Np 47491 Index document: add language

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java
template.yaml

Failing due to `413`-response (_Request Entity Too Large_) from OpenSearch

Set env var INSTITUTION_REPORT_SEARCH_PAGE_SIZE value 250

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java

Was missing affiliations parameter in search request. Added this to expected search.

InstitutionReportGenerator: Add search parameter affiliations

---

README.md

Update readMe - how to re-index, requeue IndexDLQ and DLQ-redrive

Update readMe - how to re-index, requeue IndexDLQ and DLQ-redrive

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/aws/OpenSearchClient.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/InstitutionReportGenerator.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/xlsx/ExcelWorkbookGenerator.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/FetchInstitutionReportHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/utils/AggregateResponseTestUtil.java

Changes:
- Fetch total number of candidates for given institution and year
- Split into batches of 1000
- Fetch batches in parallel

Np 47651 InstitutionReportGenerator: Parallelize fetch

---

.github/workflows/gradle.yml
template.yaml

Ticket: https://sikt.atlassian.net/browse/NP-47625
Changes:
- Adds tag to DynamoDB table marking it for backup (in environments where backup is enabled)
- Adds test reports to GitHub workflow

[np-47625] Add backup tag

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/model/document/PublicationDetails.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/NviCandidateIndexDocumentGenerator.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/UpdateIndexHandlerTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/JsonPointers.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/ExpandedResourceGenerator.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/IndexDocumentTestUtils.java

Jira task: NP-47912 Search publication abstract
- Add `publicationDetails.abstract` to nvi index document. Extract optional publication abstract from expanded resource
- Add `abstract` to `searchTerm` query

Np 47912 Index document, publication abstract

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/Aggregations.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java

Jira task: NP-47919 Institution report - return aggregations for all sub units
- Increase terms aggregation size to get aggregations for all involved organizations

Aggregation organizationApprovalStatuses, increase terms aggregation size

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/exception/IllegalCandidateUpdateException.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/service/CandidateTest.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java

Jira task: NP-48037 Missing test in NVA-NVI
Change:
- No updates should occur if an existing candidate is reported

Implement shouldNotUpdateReportedCandidate

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java

Jira task: NP-48059 CloudWath Alarm: NVI Persisting candidate failed (TransactionConflict)
Not sure if this is related to the bug mentioned above, but it is better to do this update in one transaction instead of two in method `updateCandidateAndRemovingApprovals` in `CandidateRepository`.

NP-48059 - Update candidate and remove approvals in one transaction

---

resources/nvi_111224.drawio

Update docs: Add drawio file for overview

---

buildSrc/build.gradle
buildSrc/src/main/groovy/nva.nvi.java-conventions.gradle
event-handlers/build.gradle
gradle/wrapper/gradle-wrapper.properties
nvi-commons/build.gradle
nvi-test/build.gradle

Upgrades Gradle and other dependencies.

build: Upgrade Gradle (8.6 -> 8.12)

---

buildSrc/src/main/groovy/nva.nvi.java-conventions.gradle
event-handlers/build.gradle
gradle/libs.versions.toml
index-handlers/build.gradle
index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java
nvi-commons/build.gradle
nvi-rest/build.gradle
nvi-test/build.gradle

Changes:
- Move all dependencies to common version catalogue.
- Upgrade dependencies `testcontainers`, `apache-poi`, and `opencsv`.

build: Upgrade and refactor dependencies

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/evaluator/EvaluatorService.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/evaluator/EvaluateNviCandidateHandlerTest.java

Ticket: https://sikt.atlassian.net/browse/NP-48685

[np- 48685] fix: Add null checks to period validation

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/db/DynamoDbEventToQueueHandler.java
integration-tests/src/test/java/no/sikt/nva/nvi/events/DynamoDbUpdateEventTest.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/queue/FakeSqsClient.java

Ticket: https://sikt.atlassian.net/browse/NP-49204

[np-49204] fix: Avoid sending empty message batches

---

event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/BatchScanRecoveryHandlerTest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/ReEvaluateNviCandidatesHandlerTest.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/cristin/CristinNviReportEventConsumerTest.java
index-handlers/build.gradle
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/PaginatedResultConverter.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/IndexDocumentHandlerTest.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/client/model/Organization.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/model/DbPublicationDetails.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/NviCreator.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/model/PointCalculation.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/BatchScanUtil.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/utils/Validator.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/MigrationTests.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/utils/BatchScanUtilTest.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/EnvironmentFixtures.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/SampleExpandedPublicationFactory.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/TestScenario.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/UpsertRequestBuilder.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/db/CandidateDaoFixtures.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/db/DbPublicationDetailsFixtures.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/SampleExpandedAffiliation.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/SampleExpandedPublication.java
nvi-test/src/main/java/no/sikt/nva/nvi/test/TestUtils.java
template.yaml

Changes:
- Merges duplicate methods in `SampleExpandedPublicationFactory` for building organization trees
- Adds utility methods (`hasElements`) for checking that a collection or map contains elements

[np-49350] refactor: Simplify re-used code

---

index-handlers/src/main/java/no/sikt/nva/nvi/index/query/ApprovalQuery.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/query/CandidateQuery.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/query/QueryFilterType.java
index-handlers/src/main/java/no/sikt/nva/nvi/index/utils/SearchConstants.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/apigateway/SearchNviCandidatesHandlerIntegrationTest.java
index-handlers/src/test/java/no/sikt/nva/nvi/index/aws/OpenSearchClientTest.java

Ticket: https://sikt.atlassian.net/browse/NP-49371
Changes:
- feat: Add new `filter` query parameters to cover custom requirements:
- `collaboration`: Filter by publications with at least two approving institutions involved
- `approvedByOthers`: Filter by publications that have been approved by at least one other institution
- `rejectedByOthers`:  Filter by publications that have been rejected by at least one other institution

[np-49371] feat: Add new custom filters

---

nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/CandidateRepository.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/db/PeriodRepository.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Approval.java
nvi-commons/src/main/java/no/sikt/nva/nvi/common/service/model/Candidate.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateRepositoryTest.java

Ticket: https://sikt.atlassian.net/browse/NP-49728
Changes: 
- Adds detailed logging around events that create/update significant data (candidates, approvals, reporting periods) to make future debugging easier. Note that this includes the username and organization ID where appropriate.
- Replaces a few calls to `.collect(Collectors.toList())` with `toList()`

feat: Add logging to upsert events

---

event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/RedriveUpsertDlqHandler.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/batch/RedriveUpsertDlqInput.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/persist/UpsertDlqMessageBody.java
event-handlers/src/main/java/no/sikt/nva/nvi/events/persist/UpsertNviCandidateHandler.java
event-handlers/src/test/java/no/sikt/nva/nvi/events/batch/RedriveUpsertDlqHandlerTest.java
nvi-commons/src/test/java/no/sikt/nva/nvi/common/db/CandidateRepositoryTest.java
nvi-commons/src/testFixtures/java/no/sikt/nva/nvi/common/EnvironmentFixtures.java
template.yaml

Redrive handler for processing sqs message from UpsertDlq by sending them to evaluation process.

redrive upsert dlq handler
